SET NOCOUNT ON

DELETE [KST_AuditFinding_AuditFindingImpactValue]
DELETE [KST_AuditFinding]
DELETE [KST_AuditFindingImpactValue]
DELETE [KST_AuditFindingReportedToGORMValue]
DELETE [KST_AuditFindingRootCauseValue]
DELETE [KST_AuditFindingSourceValue]
DELETE [KST_AuditFindingStatusValue]
DELETE [KST_BusinessUnitKPIScorecard_BusinessContinuityPlanningScore]
DELETE [KST_BusinessUnitKPIScorecard_ConcentrationRiskScore]
DELETE [KST_BusinessUnitKPIScorecard_FinancialIndicatorScore]
DELETE [KST_BusinessUnitKPIScorecard_OperationPerformanceScore]
DELETE [KST_BusinessUnitKPIScorecard_SecurityScore]
DELETE [KST_BusinessUnitKPIScorecard]
DELETE [KST_KPIScore_LowPerformanceReason]
DELETE [KST_KPIVolumeScore]
DELETE [KST_KPIScore]
DELETE [KST_KPIScorecardItem]
DELETE [KST_DecimalOrPercentageValue]
DELETE [KST_LowPerformanceReason]
DELETE [KST_OperationalIncident_OperationalIncidentImpactValue]
DELETE [KST_OperationalIncident]
DELETE [KST_FinancialExposureValue]
DELETE [KST_OperationalIncidentImpactValue]
DELETE [KST_OperationalIncidentReportedToGORMValue]
DELETE [KST_OperationalIncidentRootCauseValue]
DELETE [KST_OperationalIncidentSourceValue]
DELETE [KST_OperationalIncidentStatusValue]
DELETE [KST_PrivacyIncident_PrivacyIncidentMitigationCodeValue]
DELETE [KST_PrivacyIncident]
DELETE [KST_BusinessUnit]
DELETE [KST_MonthValue]
DELETE [KST_PrivacyIncidentMitigationCodeValue]
DELETE [KST_PrivacyIncidentRootCauseValue]
DELETE [KST_PrivacyIncidentStatusValue]
DELETE [KST_PrivacyIncidentTypeValue]
DELETE [KST_StatusValue]
DELETE [KST_VolumeTypeValue]
DELETE [KST_YearValue]
DELETE [Token]
DELETE [UserMappingInfo]
DELETE [ActionPermission]

SET NOCOUNT OFF
